In [2]:
import torch
import math

In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
zeros = torch.zeros(2, 3)
print(zeros)
ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
rand = torch.rand(2, 3)
print(rand)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [9]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [10]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [13]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[11.2406, 11.2083, 11.6692],
        [18.3283,  0.2118, 18.4972]], dtype=torch.float64)
tensor([[11, 11, 11],
        [18,  0, 18]], dtype=torch.int32)


In [16]:
print(torch.accelerator.is_available())
print(torch.accelerator.current_accelerator())

True
mps


In [18]:
gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
print(gpu_rand)

tensor([[0.4699, 0.1754],
        [0.7270, 0.4311]], device='mps:0')


In [19]:
print(torch.accelerator.device_count())

1


In [20]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device("cpu")
print(my_device)

mps


In [21]:
x = torch.rand(2, 3)
x.to(my_device)

tensor([[0.6865, 0.3614, 0.6493],
        [0.2633, 0.4762, 0.0548]], device='mps:0')

In [23]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)


torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [25]:
a = torch.rand(1, 20)
print(a.shape)

b = a.squeeze(0)
print(b.shape)

c = a.squeeze()
print(c.shape)

d = torch.rand(2,2)
e = d.squeeze(0)
print(d.shape)

torch.Size([1, 20])
torch.Size([20])
torch.Size([20])
torch.Size([2, 2])


In [26]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input2d = output3d.reshape(6*20, 20)
print(input2d.shape)

input1d = output3d.reshape(6*20*20)
print(input1d.shape)

torch.Size([6, 20, 20])
torch.Size([120, 20])
torch.Size([2400])


In [27]:
import numpy as np

numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
